name: Run chat bot autmatically

on:
  schedule:
    - cron: '0 5 * * *' # Every day at 5AM (UTC)
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - uses: dauletbaev/chatbot@v1
        id: bot
        with:
          telegram_bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          telegram_admin_id: ${{ secrets.TELEGRAM_ADMIN_ID }}
          geo_query: ${{ secrets.GEO_QUERY }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          openweather_api_key: ${{ secrets.OPENWEATHER_API_KEY }}
